spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-bp1n22d4fqz596a5m4o.mysql.rds.aliyuncs.com:3306/db_user?useUnicode=true&characterEncoding=utf8
    username: kyoko
    password: '#5216alsfe'
  application:
    name: user
#  cloud:
#    config:
#      name: ticket-config #配置文件名
#      label: master #分支
#      discovery:
#        service-id: config-server #
#        enabled: true #启用发现配置

mybatis-plus:
  mapper-locations: classpath:/mybatis/mappers/*.xml
  type-aliases-package: com.woniuxy.user.entity

server:
  port: 8094

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    root: info