spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-bp1n22d4fqz596a5m4o.mysql.rds.aliyuncs.com:3306/db_cinema?useUnicode=true&characterEncoding=utf8
    username: kyoko
    password: '#5216alsfe'
  application:
    name: cinema

mybatis-plus:
  mapper-locations: classpath:/mybatis/mappers/*.xml
  type-aliases-package: com.woniuxy.cinema.entity

server:
  port: 8091

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    root: info