spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-bp1n22d4fqz596a5m4o.mysql.rds.aliyuncs.com:3306/db_order?useUnicode=true&characterEncoding=utf8
    username: kyoko
    password: '#5216alsfe'
  application:
    name: order
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

mybatis-plus:
  mapper-locations: classpath:/mybatis/mappers/*.xml
  type-aliases-package: com.woniuxy.order.entity

server:
  port: 8093

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    root: info

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000



