spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: users
          uri: lb://user
          predicates:
            - Path=/user/**
        - id: orders
          uri: lb://order
          predicates:
            - Path=/order/**
        - id: auths
          uri: lb://auth
          predicates:
            - Path=/auth/**
      httpclient:
        response-timeout: 60000

server:
  port: 80

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


